### ISSUE TITLE
Code for fig1

### ISSUE THREAD

**Issue by JunMa11** [ahukui/BOWDANet#1]
Dear @ahukui ,

Thanks for sharing the code. I very enjoy reading your paper.
Would it be possible for you to release the code for fig1?

![image](https://user-images.githubusercontent.com/19947331/63212557-74ff5100-c0d4-11e9-8c87-515abe42b7e0.png)

Looking forward to your reply.

Best,
Jun

**Comment by ahukui** [comment]
Of course! The t-SNE code have been upload.

**Comment by JunMa11** [comment]
Thank you very much.
